language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "V/xFGrW22kzM50Cm64MxBdc5BxKTMbhLPBEfZQ3tqEbssRDt8OEBnwbXXftJMUHq98mYxy2ss4/Xb3nBaLMm6p0PmWQ5E1p5n+7PYsRTYZmR50w17wyhXSPKTwhtzcf3HMNYHpZguH7IHijUUGfChBVj5UMkUiv7QHr1MfirZUaV5AUeOiOh4UeGkPvj5NHXehBBl32ijlRGUP7D01EOQRrWkYOojvmbg2m6HRhuaVqrzbm1h4+qiyFPajf2/xBUskWjeYg6gU3j/6yQ8osB4qtffEHIWLr5mQqjHLy/avzPVsuMXiSvY98GOk62UMGq1W+diMpRYz/5NLuV8EfdK5vyP6Utki4SZ5t5oIYJARwY1/RNZtOw7VwwoxL2GlSRRGsI/JhrOYSJ83W8+TlTcnbs/3a0IR4/h1G7qrTCca3ph2rzQml5Bhl65rMoTtoArv2ALi4a3FotopHfuLbqlh9u1aSvSZr91LBHKWv40rrIsBKk9NPpcBl8fpZUjLP3XkZOReuGCFmpqPJFmSh/wJSEeSZs4J+V4ujhILMddQDbM23PRUANrbe/COcEgnYAlm32bpABm22EDeXnrQjyEfsMX4uENSFG2kME0lq5gBAs7x99CfWK/Anp2w5/K/7lTzda/rCQ43JBfOaeoGP5E13+Y3vndfVK2trHE94i1c4="
