language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "OsfTbXoZw7tH3E/8/GjTxKijCL6EU3kPpJZSGixaFGD+TpRfgfnYQFKfl8o6WDjbUH4bAxIVzkvEeXpxUoxQJNQmiexoT9uZikT6dOAHPFtMloqMkvmQtD5c6PATnIFxP+GHszCFA5J5B5RqqeL7MTxxcOPxWsl1/bYcZNJON7N4OicHbJiWS29aaG+IC7GszZxxdnSldR6YbCZSPyJB1GW7Ao9aJrs/Q474uFvC8JoL6lVYkeFoefecPvYnHigmkRzvFgksbDw/2NOsCj5BpcYWfGxS3VMMOOEpUuFlNtbTInY2zM9mYxQi7d/saxusvB5Y7u1Wm5uVAq1hFYkmM4kEdGlRV5sM72Vfp55uuu4H2MGfhy9YgXSIxaBZg3MIVN1rdYuHBDZdXgmoMLAAb9MUusv4Dh7oAJzxxLDEFqD6IfWth/aft7SsbMq5MuuKSiszFqF9gG8i16qh3MT09KH80TuvbfqIX6Lf08kJfkKRCLhuTwT5trK+9EWeOICOMFF8rlUhHXP7atJW2rkFSnfxnjGM8lOZarG1lnbZ8QWQm246l8AMyslsdQsCgVIma/G5UAZiy0nHXSyyI2rZ2qx8OLCD2fVkOYHqVUDfuGdysyJEVR7afzT1d2nS0/rIYckzdwTcE4SAHmrsvUxv5Tb8WrbHgwBCK/aox+0wz2M="
